UPDATE `test`.`specializations` SET `name` = 'acupuncture' WHERE (`spec_id` = '1');
UPDATE `test`.`specializations` SET `name` = 'bariatric surgery' WHERE (`spec_id` = '2');
UPDATE `test`.`specializations` SET `name` = 'beauty salon treatments' WHERE (`spec_id` = '3');
UPDATE `test`.`specializations` SET `name` = 'cardiology' WHERE (`spec_id` = '4');
UPDATE `test`.`specializations` SET `name` = 'chiropractic' WHERE (`spec_id` = '5');
UPDATE `test`.`specializations` SET `name` = 'dentistry' WHERE (`spec_id` = '6');
UPDATE `test`.`specializations` SET `name` = 'dermatology' WHERE (`spec_id` = '7');
UPDATE `test`.`specializations` SET `name` = 'ear nose and throat' WHERE (`spec_id` = '8');
UPDATE `test`.`specializations` SET `name` = 'eye care' WHERE (`spec_id` = '9');
UPDATE `test`.`specializations` SET `name` = 'fertility' WHERE (`spec_id` = '10');
UPDATE `test`.`specializations` SET `name` = 'gastroenterology' WHERE (`spec_id` = '11');
UPDATE `test`.`specializations` SET `name` = 'general practice' WHERE (`spec_id` = '12');
UPDATE `test`.`specializations` SET `name` = 'hair loss treatments' WHERE (`spec_id` = '13');
UPDATE `test`.`specializations` SET `name` = 'holistic health' WHERE (`spec_id` = '14');
UPDATE `test`.`specializations` SET `name` = 'laser eye surgery' WHERE (`spec_id` = '15');
UPDATE `test`.`specializations` SET `name` = 'massage therapy' WHERE (`spec_id` = '16');
UPDATE `test`.`specializations` SET `name` = 'medical aesthetics' WHERE (`spec_id` = '17');
UPDATE `test`.`specializations` SET `name` = 'neurology' WHERE (`spec_id` = '18');
UPDATE `test`.`specializations` SET `name` = 'obstetrics / gynaecology' WHERE (`spec_id` = '19');
UPDATE `test`.`specializations` SET `name` = 'oncology' WHERE (`spec_id` = '20');
UPDATE `test`.`specializations` SET `name` = 'organ transplants' WHERE (`spec_id` = '21');
UPDATE `test`.`specializations` SET `name` = 'orthopaedics' WHERE (`spec_id` = '22');
UPDATE `test`.`specializations` SET `name` = 'osteopathy' WHERE (`spec_id` = '23');
UPDATE `test`.`specializations` SET `name` = 'physiotherapy' WHERE (`spec_id` = '24');
UPDATE `test`.`specializations` SET `name` = 'plastic surgery' WHERE (`spec_id` = '25');
UPDATE `test`.`specializations` SET `name` = 'psychiatry' WHERE (`spec_id` = '26');
UPDATE `test`.`specializations` SET `name` = 'psychology' WHERE (`spec_id` = '27');
UPDATE `test`.`specializations` SET `name` = 'psychotherapy' WHERE (`spec_id` = '28');
UPDATE `test`.`specializations` SET `name` = 'urology' WHERE (`spec_id` = '29');
